### ISSUE TITLE
does it have to check for columns for the processing flag?

### ISSUE THREAD

**Issue by ilpoldo** [jstorimer/delayed_paperclip#10]
It's a bit of a feature request:
I have my own processing flag set in the model and used an embedded association á là [railscast 189](http://railscasts.com/episodes/189-embedded-association).

I'd like to add methods in the model like _attachment_name__processing that deal with my flag rather than having two flags: one for delayed paperclip and one for the encoding api.
The problem is that dp checks for the existence of the column, not for a resond_to

Why is there a check for an actual column? Would you consider accepting a patch that alters the beahviorur?

**Comment by jstorimer** [comment]
The reason that I check for a column is that I'm going to try and set the value of that column. If I check for respond_to?("#{attachment_name}_processing") then I also have to check for respond_to?(#{attachment_name}_processing=").

I would definitely consider accepting a patch that accommodates your situation. My thoughts: Use respond_to?("#{attachment_name}_processing") but then do something like #{attachment_name}_processing!, #{attachment_name}_processed! which would set the value of the column by default, but can be overridden by devs such as yourself who need different behaviour.

**Comment by ilpoldo** [comment]
yeah. makes sense to me. I'll fork and patch after lunch!
