### ISSUE TITLE
Only one image processed when uploading multiple files

### ISSUE THREAD

**Issue by McGinTech** [jstorimer/delayed_paperclip#11]
When I upload multiple files, only the last one gets processed successfully.  The other original image is in S3, but no thumbnails.  Sometimes I get the following error in delayed_jobs.last_error and sometimes I get no error and the jobs are auto-deleted from the database.

instance_klass: Image
instance_id: 38
attachment_name: :file
 | The specified key does not exist.
/usr/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/error.rb:38:in `raise'
/usr/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/base.rb:72:in`request'
/usr/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/base.rb:88:in `get'
/usr/lib/ruby/gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/object.rb:134:in`value'
/usr/lib/ruby/gems/1.8/gems/paperclip-2.3.1.1/lib/paperclip/storage.rb:193:in `to_file'
/usr/lib/ruby/gems/1.8/gems/paperclip-2.3.1.1/lib/paperclip/attachment.rb:212:in`reprocess!'
/usr/lib/ruby/gems/1.8/gems/delayed_paperclip-0.6.5/lib/delayed/jobs/delayed_paperclip_job.rb:4:in `perform'
/usr/lib/ruby/gems/1.8/gems/delayed_paperclip-0.6.5/lib/delayed/jobs/delayed_paperclip_job.rb:16:in`process_job'
/usr/lib/ruby/gems/1.8/gems/delayed_paperclip-0.6.5/lib/delayed/jobs/delayed_paperclip_job.rb:3:in `perform'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:235:in`invoke_job'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:113:in `run_with_lock'
/usr/lib/ruby/1.8/timeout.rb:56:in`timeout'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:113:in `run_with_lock'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:10:in`realtime'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:112:in `run_with_lock'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:173:in`reserve_and_run_one_job'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:172:in `each'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:172:in`reserve_and_run_one_job'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:219:in `work_off'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:218:in`times'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/job.rb:218:in `work_off'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/worker.rb:30:in`start'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:10:in `realtime'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/worker.rb:29:in`start'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/worker.rb:26:in `loop'
/usr/lib/ruby/gems/1.8/gems/delayed_job-1.8.5/lib/delayed/worker.rb:26:in`start'
script/delayed_job:24
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:215:in `call'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:215:in`start_proc'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/daemonize.rb:192:in `call'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/daemonize.rb:192:in`call_as_daemon'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:219:in `start_proc'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/application.rb:255:in`start'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/controller.rb:69:in `run'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:188:in`run_proc'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in `call'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons/cmdline.rb:105:in`catch_exceptions'
/usr/lib/ruby/gems/1.8/gems/daemons-1.0.10/lib/daemons.rb:187:in `run_proc'
script/delayed_job:13

**Comment by McGinTech** [comment]
Also, if I call reprocess!, it only works on the same file that was successfully processed by delayed_job, even though reprocess! returns true on all files.

And, .url always gives me the default url.

**Comment by McGinTech** [comment]
I tried changing 

has_attached_file :file

to 

has_attached_file :cfile

just to see if there was something quirky with :file like there is if you use :attachment.

Now I get: instance_klass: Image
instance_id: 49
attachment_name: :cfile
 | undefined method `cfile' for #<Image id: 49, classified_id: 443>

**Comment by varyform** [comment]
I have similar issue, but with file system storage and no error in delayed_jobs.last_error: job just disappear.

**Comment by varyform** [comment]
Please ignore my comment :). Solved by killing old delayed_job instance.

**Comment by kueda** [comment]
If anyone's still reading, I got around this issue by removing paperclup validations from the model.
