### ISSUE TITLE
Confusion dealing with delayed_paperclip

### ISSUE THREAD

**Issue by richardaday** [jstorimer/delayed_paperclip#12]
Hey,

All the blogs and documentation for the exact use case is a little confusing.

Does delayed_paperclip _only_ delay the resizing of images?  Or does it delay the file upload to s3 as well?

From my testing it seems that it does not delay the file upload to s3.  Is that true?

**Comment by jstorimer** [comment]
delayed_paperclip only delays the resizing of images. It DOES NOT delay the upload to s3.

This comment explains the motivation behind that choice: http://jstorimer.com/ruby/2010/01/30/delayed-paperclip.html#comment-39058867
