### ISSUE TITLE
warning: parenthesize argument(s) for future version

### ISSUE THREAD

**Issue by laurynas** [jstorimer/delayed_paperclip#13]
I'm getting some warnings:

<pre>
/usr/lib/ruby/gems/1.8/gems/delayed_paperclip-0.6.5/lib/delayed/paperclip.rb:88: warning: parenthesize argument(s) for future version  
/usr/lib/ruby/gems/1.8/gems/delayed_paperclip-0.6.5/lib/delayed/paperclip.rb:89: warning: parenthesize argument(s) for future version
</pre>

**Comment by jstorimer** [comment]
I can't reproduce this, which ruby interpreter/version are you using?

**Comment by laurynas** [comment]
ruby 1.8.6 (2007-09-24 patchlevel 111) [i486-linux]
Default on Ubuntu Hardy.

**Comment by jstorimer** [comment]
I'm having trouble getting that interpreter running on my mac. If you write a patch to get rid of the warnings I'd be happy to pull it in.

**Comment by laurynas** [comment]
Hi,
strange - seems that warnings occurs only if I'm using 0.6.5 gem. 
I wanted to write patch and installed deplayed_paperclip plugin - no warnings. Maybe you already fixed it ;)

Best wishes,
Laurynas
