### ISSUE TITLE
processing column doesn't switch to false

### ISSUE THREAD

**Issue by nir0** [jstorimer/delayed_paperclip#16]
i added image_processing column to my model, and now it stays true, though processing is finished, images are ready. do i need to implement flag switcher by hand?
==  AddPhotoProcessing: migrating =============================================
-- add_column(:photos, :image_processing, :boolean)
   -> 0.0014s
==  AddPhotoProcessing: migrated (0.0015s) ====================================

added a photo

irb(main):002:0> Photo.all.collect{|p|[p.id, p.image_processing]}
=> [[5, nil], [6, nil], [7, nil], [8, nil], [10, nil], [11, nil], [13, true]]

**Comment by jstorimer** [comment]
You don't need to implement a 'flag switcher' by hand, the gem should auto-detect that you have the processing column and set it for you. 

What are the names of the other columns on that model?

**Comment by nir0** [comment]
nir0@Darkstar:~$ cat yapok/db/schema.rb
    ...
    create_table "photos", :force => true do |t|
      t.integer  "user_id"
      t.string   "name"
      t.integer  "rubrick_id"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.string   "image_file_name"
      t.string   "image_content_type"
      t.integer  "image_file_size"
      t.datetime "image_updated_at"
    end
    ...

gem sets the column to true, and Delayed::Job doesn't set it back to false
p.s. sorry, i deleted this field to make my app working, but i'll bring image_processing back as soon as it will work for me

**Comment by nateleavitt** [comment]
This works fine for me.  Are you sure your workers are processing?
