### ISSUE TITLE
undefined method `constantize' for 56:Fixnum

### ISSUE THREAD

**Issue by tsukhani** [jstorimer/delayed_paperclip#2]
I get the following error after I tried running delayed_paperclip jobs via script/job_runner:

undefined method `constantize' for 56:Fixnum
/usr/local/lib/ruby/gems/1.8/gems/delayed_paperclip-0.5.0/lib/delayed/jobs/delayed_paperclip_job.rb:3:in`perform'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:215:in `invoke_job'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:93:in`run_with_lock'
/usr/local/lib/ruby/1.8/timeout.rb:62:in `timeout'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:93:in`run_with_lock'
/usr/local/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:92:in`run_with_lock'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:153:in `reserve_and_run_one_job'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:152:in`each'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:152:in `reserve_and_run_one_job'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:199:in`work_off'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:198:in `times'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/job.rb:198:in`work_off'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/worker.rb:28:in `start'
/usr/local/lib/ruby/1.8/benchmark.rb:308:in`realtime'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/worker.rb:27:in `start'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/worker.rb:24:in`loop'
/usr/local/lib/ruby/gems/1.8/gems/delayed_job-1.8.4/lib/delayed/worker.rb:24:in `start'
script/job_runner:4

**Comment by jstorimer** [comment]
Fixed in version 0.5.1. http://gemcutter.org/gems/delayed_paperclip
Thanks for the report :)

**Comment by tsukhani** [comment]
yup, it is fixed..thanks!
