### ISSUE TITLE
Couldn't find Photo with ID=X

### ISSUE THREAD

**Issue by gmgreg** [jstorimer/delayed_paperclip#22]
I'm using delayed_paperclip (tried both 0.6.5 and recently 0.7.0) with paperclip on Heorku using S3 as storage.  

I have a site where users can upload multiple photos for storage with a single put.  The photos are then  re-sized into two sizes.  With both versions (0.6.5 and 0.7.0) it would work spottily when users sent more than one photo in an upload (e.g. 5 photos).  Some photos would get background processed and others would fail.  

When I look through the logs I've put some statements in so I can see that the Resque.enqueue statements are being called.  However, often a few of the enqueued processes simply do not run or the enqueue itself is failing.

I should also note its a separate worker that may be processing the image (i.e. a different thread, potentially on a different machine).  That worker can see the resque queue though, and can get the file from S3.  When I run a reprocess! manually from the heroku console it works fine.

**Comment by jstorimer** [comment]
Dup of #26.
