### ISSUE TITLE
how can i custom :path and :url ?

### ISSUE THREAD

**Issue by sxhyll** [jstorimer/delayed_paperclip#23]
like this:

 ....
before_create :randomize_file_name

def randomize_file_name
   extension = File.extname(avatar_file_name).downcase
   self.avatar.instance_write(:file_name, "#{ActiveSupport::SecureRandom.hex(16)}#{extension}")
 end

has_attached_file :avatar,
                    :styles => {:medium => "300x300>", :thumb => "100x100>"}#,
                     :url => "/system/:attachment/#{Time.now.year}/w#{Time.now.strftime("%W")}/:basename_:style.:extension",
                     :path => ":rails_root/public/system/:attachment/#{Time.now.year}/w#{Time.now.strftime("%W")}/:basename_:style.:extension"
....

and then:

only have :original pic , and :medium pic,  :thumb pic  not  created, i dont know why ?

Thank you very much ! my english very pool, sorry

by -- Kevin Li

**Comment by owahab** [comment]
Well, this has nothing to do with delayed_paperclip, this would be better asked in paperclip issue tracker.
However, I haven't tried changing :path and :url this way, I usually use interpolations.

**Comment by sxhyll** [comment]
ok, let me have a try , thans again.

2011/6/24 owahab <
reply@reply.github.com>
