### ISSUE TITLE
Unable to setup test environment

### ISSUE THREAD

**Issue by owahab** [jstorimer/delayed_paperclip#24]
Hello Jesse,

Trying to write some tests for issue #21 and following the CONTRIBUTING file, I got an exception when running `rake test`.

Full log:

<pre>
~/Code/Ruby/gems/delayed_paperclip% bundle install
Fetching source index for http://rubygems.org/
Using activesupport (3.0.9) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.9) 
Using arel (2.0.10) 
Using tzinfo (0.3.28) 
Installing activerecord (3.0.9) 
Using cocaine (0.1.0) 
Using daemons (1.1.4) 
Using delayed_job (2.1.4) 
Using paperclip (2.3.12) 
Using delayed_paperclip (0.6.5) from source at /Users/owahab/Code/Ruby/gems/delayed_paperclip 
Installing json (1.5.3) with native extensions 
Installing mocha (0.9.12) 
Installing rack (1.3.0) 
Installing redis (2.2.1) 
Installing redis-namespace (1.0.3) 
Installing tilt (1.3.2) 
Installing sinatra (1.2.6) 
Installing vegas (0.1.8) 
Installing resque (1.17.1) 
Using sqlite3 (1.3.3) 
Using sqlite3-ruby (1.3.3) 
Using bundler (1.0.10) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
~/Code/Ruby/gems/delayed_paperclip% rake test
(in /Users/owahab/Code/Ruby/gems/delayed_paperclip)
/Users/owahab/.rvm/rubies/ruby-1.9.2-p180/bin/ruby -I"lib:lib" "/Users/owahab/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/delayed_paperclip_test.rb" "test/resque_paperclip_test.rb" 
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- test/test_helper (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from test/delayed_paperclip_test.rb:1:in `<top (required)>'
    from /Users/owahab/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `load'
    from /Users/owahab/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `block in <main>'
    from /Users/owahab/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `each'
    from /Users/owahab/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1): [/Users/owahab/.rvm/rubies/ruby-1.9.2-p180/...]

(See full trace by running task with --trace)
zsh: exit 1     rake test
~/Code/Ruby/gems/delayed_paperclip% 
</pre>

**Comment by owahab** [comment]
My little quick dirty hack to get around this:

```
diff --git a/Rakefile b/Rakefile
index f25675f..8243676 100644
--- a/Rakefile
+++ b/Rakefile
@@ -9,6 +9,7 @@ task :default => :test
 desc 'Test the paperclip plugin.'
 Rake::TestTask.new(:test) do |t|
   t.libs << 'lib'
+  t.libs << 'test'
   t.pattern = 'test/**/*_test.rb'
   t.verbose = true
 end
diff --git a/test/delayed_paperclip_test.rb b/test/delayed_paperclip_test.rb
index e7c0165..87634ba 100644
--- a/test/delayed_paperclip_test.rb
+++ b/test/delayed_paperclip_test.rb
@@ -1,4 +1,4 @@
-require 'test/test_helper'
+require 'test_helper'
 require 'delayed_job'
 Delayed::Worker.backend = :active_record

diff --git a/test/resque_paperclip_test.rb b/test/resque_paperclip_test.rb
index 8125e02..c99c766 100644
--- a/test/resque_paperclip_test.rb
+++ b/test/resque_paperclip_test.rb
@@ -1,4 +1,4 @@
-require 'test/test_helper'
+require 'test_helper'
 gem 'resque'
 require 'resque'
```

**Comment by jstorimer** [comment]
Yeah, this is the proper way to do it. Want to provide a pull request or format this with git-format-patch so you can get credit for it?

**Comment by owahab** [comment]
Of course not, just commit it please.
