### ISSUE TITLE
"Stack level too deep" when has_attached_file :attachment

### ISSUE THREAD

**Issue by mikelovesrobots** [jstorimer/delayed_paperclip#3]
I ran into an amusing error.  If your paperclip attachment is named "attachment", then it blows up with a "stack level too deep" exception when uploading a file.  The culprit is this:

```
(lib/delayed/paperclip.rb)
define_method "#{name}_changed?" do
  file_attachment_changed?(name)
end
```

When #{name} is :attachment, it ends up overwritting Delayed::Paperclip::InstanceMethods#attachment_changed?

I recommend making a note in the readme that you shouldn't name your attachment :attachment, or renaming Delayed::Paperclip::InstanceMethods#attachment_changed? in your source.

Thanks for making delayed_paperclip.  I really appreciate this excellent plugin.

**Comment by jstorimer** [comment]
Fixed. Thanks.
