### ISSUE TITLE
Incompatibility with Paperclip 2.3.15?

### ISSUE THREAD

**Issue by sat** [jstorimer/delayed_paperclip#30]
I recently did a bundle update and my paperclip version updated to the recently released 2.3.15.

Following the update, i noticed some weird behaviour with the delayed paperclip jobs.  Once the job was processed it would reinitialize the same job in the DB and then process the image again, over and over again and never stop.

```
DelayedPaperclipJob completed after 3.6699
DelayedPaperclipJob completed after 3.4298
DelayedPaperclipJob completed after 3.4421
DelayedPaperclipJob completed after 3.9339
DelayedPaperclipJob completed after 4.0015
DelayedPaperclipJob completed after 5.0911
```

The initial job would be removed from the database (but replaced with another one at that time).  Therefore, I would never get the notification on completion of the jobs:

```
1 jobs processed at 0.9559 j/s
```

I tried processing an image without using delayed_paperclip via paperclip 2.3.15 and everything works as expected.

Has anyone else noticed this?  I ended up rolling back to paperclip 2.3.12 and delayed_paperclip behaves as desired.

**Comment by jstorimer** [comment]
That's pretty weird. The only reason I could imagine that the job is continually retried is if it fails for some reason and is picked up by the DJ retry logic. If you inspect these jobs in the database do you have any indication they are failing? Look at the number of `attempts` and the `last_error`.

**Comment by Bertg** [comment]
I had seen an issue with paperclip 2.3.15 and the 0.6.x code of delayed_paperclip. 

In this paperclip release, they added a touch to the update_at attribute of the attachment just before calling the processing. The halt system would then be activated, as the DelPaper attachment_changed? would return true; and thus also enqueue the task.

This is resolved in the refactoring.
