### ISSUE TITLE
Rspec not enqueuing the processing job

### ISSUE THREAD

**Issue by bastien** [jstorimer/delayed_paperclip#33]
After upgrading to the latest version of delayed_paperclip (from 0.6.5 to 0.7.2), when testing a custom paperclip processor with, the processing was never perfomed. The reason was that  delayed_paperclip uses the after_commit callback. Since rspec uses transactional fixtures the after_commit is not triggered.

The solution to this problem for me was to disable the transactional fixtures for that single spec:

``` ruby
describe "with transactional fixtures disabled" do
  self.use_transactional_fixtures = false

  after(:each) do
    # Cleanup
  end

  it "should run my custom processor" do
    # Assigning file to model
    Delayed::Worker.new.work_off # Launching DJ worker
    # Test that the processing has been performed
  end
end
```

It took me some time to figure it out, hope this helps.

**Comment by Bertg** [comment]
An other fix for the after_commit testing is this neat patch: https://gist.github.com/990357.

**Comment by mstump** [comment]
The monkey patch worked great for me, it's written up in:  http://outofti.me/post/4777884779/test-after-commit-hooks-with-transactional-fixtures

Thanks!
