### ISSUE TITLE
delayed destroy

### ISSUE THREAD

**Issue by jaredmoody** [jstorimer/delayed_paperclip#38]
I've found in one of my apps that waiting for s3 to respond to destroy requests for multiple thumbnails sometimes takes more time than I want the user to have to wait.  Would you be open to a patch that handles deleting files via delayed job or provides an option to do so?

**Comment by jstorimer** [comment]
I'd be open to this. I'd probably release as an option that is off by default. Then depending on feedback it may be turned on by default in a new release.
