### ISSUE TITLE
Thumb styles are not always correct when dealing w/ models/submodels

### ISSUE THREAD

**Issue by davidjbeveridge** [jstorimer/delayed_paperclip#39]
I have 2 models, one of which is a subclass of the other.  They use different styles for the same attachment.

When the parent model processes an image as a delayed_job, it is sometimes processed using the styles specified in the child class.

I'm not sure if this behavior is a problem with delayed_paperclip, delayed_job, or paperclip.  I'll post an update if/when I find out more.

**Comment by Bertg** [comment]
Hi,

Have you been able to find out more? 

delayed_paperclip is not really doing anything to the style-logic implemented by paperclip. It would surprise me if it had anything to do with this gem.

Maybe you could have a look at delayed_job and double check witch class gets loaded?
