### ISSUE TITLE
[attachment_name]_processing column causes strange behavior

### ISSUE THREAD

**Issue by jandjshi** [jstorimer/delayed_paperclip#4]
After added [attachment_name]_processing column, paperclip would first upload the image to [rails root]/public/main_photos/original/missing.png (my attachment is name main_photo) instead of the usual public/system/main_photos/:id/original/. Then when Delayed_job kicked off paperclip, which processed the thumbnail image and put it into /public/main_photos/thumb/missing.png, instead of the usual public/system/main_photos/:id/thumb/

I am running paperclip gem 2.3.1.1, rails 2.3.4, delayed_paperclip gem 0.6.1

**Comment by jstorimer** [comment]
Thanks for the bug report. We were alias_method_chaining a method in Paperclip and forgot to add an important conditional.

I've fixed it and bumped the version to 0.6.2.

**Comment by jandjshi** [comment]
verify worked!
