### ISSUE TITLE
paperclip 2.3.8 as last working - no delayed_paperclip!

### ISSUE THREAD

**Issue by kredmer** [jstorimer/delayed_paperclip#40]
Hi,
due a problem described here: https://github.com/thoughtbot/paperclip/issues/450
I am not able to use delayed_paperclip , because it needs  paperclip >= 2.39 (https://github.com/jstorimer/delayed_paperclip/issues/36)

I tried with (working) delayed job and also with (working) resque (of course not both together!).

Is there on older version of delayed_paperclip not needing post_processing?

Thanks,
Karsten

**Comment by Bertg** [comment]
The 0.6.5 version should work for you.

**Comment by kredmer** [comment]
Thanks. This problem is solved and now we go on with tempfile ->https://github.com/jstorimer/delayed_paperclip/issues/41
