### ISSUE TITLE
Paperclip 2.4.x

### ISSUE THREAD

**Issue by atd** [jstorimer/delayed_paperclip#43]
Are there any plans to support paperclip 2.4.x?

**Comment by Bertg** [comment]
The idea is that this gem stays compatible with the latest version of paperclip.

I'm currently very busy for some other projects. I'll try to have a look this week. I will gladly accept pull requests for 2.4.x compatibility.

**Comment by ghost** [comment]
I would like to see this also, currently spree 0.70.1 depends on paperclip 2.4.1 so i cant use delayed_paperclip, which i would like to do, thanks!

**Comment by Bertg** [comment]
Hi,

I added a bunch of version/2.4.X branches of this gem. It seems that up to 2.4.2 the current test passed fine. I added a little fix for 2.4.3 and then all the way up to 2.4.5 everything works fine (in the tests).

Could you verify this? If you have any additional errors, could you add tests for them or describe them in detail here?

I would also like you to have a look at this ticket (https://github.com/jstorimer/delayed_paperclip/issues/46) which discusses the versioning of this gem, so we can provide better compatibility with paperclip overall.

**Comment by tommeier** [comment]
+1 (awesome to find this being thought about already :)

**Comment by tommeier** [comment]
2.4.5 with rails 3.1.1, ruby 1.9.2 verified
