### ISSUE TITLE
Thumb styles not created when using #{attachment_name}_processing

### ISSUE THREAD

**Issue by pmoran** [jstorimer/delayed_paperclip#44]
I can successfully generate thumb styles when an avatar_processing column is **not** present, however adding the column results in only the original file being saved. When debugging, it appears that the original image is not present at the time Attachment.process_delayed! is called, whereas without using the avatar_processing column the original does exist.

I am using delayed_paperclip 0.7.2, Paperclip 2.3.16 and Rails 3.1.1. Any help appreciated - thanks.

**Comment by Bertg** [comment]
Hi,

Could you provide a test for this? Currently - i believe - our test are covering this, and I see no failures.

**Comment by pmoran** [comment]
Could be something dumb I'm doing, but this app demonstrates the issue I'm seeing https://github.com/pmoran/delayed_paperclip_sample. Thanks.

**Comment by pmoran** [comment]
I've tried my app with master and the issue goes away - looks like it's been fixed for Rails 3.1. Attachment processing now working. Nice work!
