### ISSUE TITLE
2.4.5.0 -> Only working with explicit 'include DelayedPaperclip::Glue'

### ISSUE THREAD

**Issue by tommeier** [jstorimer/delayed_paperclip#49]
Hi, 

Latest version (2.4.5.0) is working great with the latest Paperclip (2.4.5).

However, on load of a rake task or anything, with Rails 3.1 it is failing to run the Railtie for DelayedPaperclip .

For example : 

``` Ruby
class Image < ActiveRecord::Base
   has_attached_file :image

  process_in_background :image
end
```

``` Bash
bundle exec rake paperclip:refresh CLASS=Image
rake aborted!
undefined method `process_in_background' for #<Class:0x007f904cbed0c8>
```

Then explicitly including DelayedPaperclip::Glue it works : 

``` Ruby
class Image < ActiveRecord::Base
   include DelayedPaperclip::Glue

   has_attached_file :image

  process_in_background :image
end
```

Not sure why the Rails init commands aren't working yet...

**Comment by tommeier** [comment]
ok, with a minor rejig of the railtie.rb it works. And specs are passing.. Though i'm a little rusty on my Test::Unit, and i'm not sure what test to write, as it is forcibly including it in test_helper.rb with the insert command.

``` Ruby
require 'delayed_paperclip'

module DelayedPaperclip
  if defined?(::Rails::Railtie)
    class DelayedPaperclipRailtie < ::Rails::Railtie
      initializer 'delayed_paperclip.extends' do
        ActiveSupport.on_load :active_record do
          ActiveRecord::Base.send(:include, DelayedPaperclip::Glue)
        end
      end
    end
  end

  class Railtie
    def self.insert
      ActiveRecord::Base.send(:include, DelayedPaperclip::Glue)
      Paperclip::Attachment.send :include, DelayedPaperclip::Attachment
    end
  end

end
```

**Comment by Bertg** [comment]
Hi,

I could indeed easily confirm your issue. And thanks for your fix.

I've applied a similar [fix](https://github.com/jstorimer/delayed_paperclip/commit/61eb0d2d0eacee70350a22460032fed024c54a0a) on master (not exactly the same). Could you confirm this fixes your issue (I think it should). I'll release shortly after that, or around noon tomorrow (GMT+1); whatever comes first ;)

**Comment by tommeier** [comment]
Perfect works great for me, definite candidate for first point release! Thanks!
