### ISSUE TITLE
undefined method `url' for class `Paperclip::Attachment'

### ISSUE THREAD

**Issue by brendon** [jstorimer/delayed_paperclip#5]
I make use of the the :url option for my paperclip attachments. Could this be causing this? The stack trace doesn't seem to help much. It actually prevents passenger from starting:

0   /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/module/aliasing.rb  33  in `alias_method'
1   /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/module/aliasing.rb  33  in`alias_method_chain'
2   /Users/brendon/Projects/SpikeAtSchool/vendor/plugins/delayed_paperclip/lib/delayed/paperclip.rb 105 
3   /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in `gem_original_require'
4   /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in`require'
5   /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb  156 in `require'
6   /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb  521 in`new_constants_in'
7   /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb  156 in `require'
8   /Users/brendon/Projects/SpikeAtSchool/vendor/plugins/delayed_paperclip/lib/delayed_paperclip.rb 1   
9   /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in`gem_original_require'
10  /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in `require'
11  /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb  156 in`require'
12  /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb  521 in `new_constants_in'
13  /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb  156 in`require'
14  /Users/brendon/Projects/SpikeAtSchool/vendor/plugins/delayed_paperclip/rails/init.rb    1   in `evaluate_init_rb'
15  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/rails/plugin.rb 158 in`evaluate_init_rb'
16  /Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/kernel/reporting.rb 11  in `silence_warnings'
17  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/rails/plugin.rb 154 in`evaluate_init_rb'
18  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/rails/plugin.rb 48  in `load'
19  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/rails/plugin/loader.rb  38  in`load_plugins'
20  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/rails/plugin/loader.rb  37  in `each'
21  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/rails/plugin/loader.rb  37  in`load_plugins'
22  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/initializer.rb  369 in `load_plugins'
23  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/initializer.rb  165 in`process'
24  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/initializer.rb  113 in `send'
25  /Library/Ruby/Gems/1.8/gems/rails-2.3.5/lib/initializer.rb  113 in`run'
26  /Users/brendon/Projects/SpikeAtSchool/config/environment.rb 16  
27  /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in `gem_original_require'
28  /Library/Ruby/Site/1.8/rubygems/custom_require.rb   31  in`require'

**Comment by brendon** [comment]
Nevermind, I was using the plugin, and because of its name, it loads before paperclip (which I was also using the plugin of) :)

**Comment by jstorimer** [comment]
thought so, good find

**Comment by shuber** [comment]
This is still an issue when trying to unpack gems including delayed_job. It works if you wrap the block of code starting here: 

http://github.com/jstorimer/delayed_paperclip/blob/master/lib/delayed/paperclip.rb#L88

with something like "if Object.const_defined?('Paperclip')"

**Comment by jstorimer** [comment]
I think this is because delayed_paperclip tries to alias_method_chain a method in Paperclip::Attachment but it wasn't properly requiring 'paperclip' on load, so you had to manage the load order of libraries yourself.

I added "require 'paperclip'" when loading the plugin and bumped the version to 0.6.3. Let me know if this fixed the issue for you.

**Comment by shuber** [comment]
That works, thanks!
