### ISSUE TITLE
Cannot find file at Amazon S3.

### ISSUE THREAD

**Issue by NilsHaldenwang** [jstorimer/delayed_paperclip#65]
Hey there,

when trying to use the gem there occurs an error within the worker:

```15:18:11 worker.1  | *\* [15:18:11 2012-04-20] 15872: (Job{paperclip} | DelayedPaperclip::Jobs::Resque | ["ImageUpload", 34,     "image"]) failed: 
# <Errno::ENOENT: No such file or directory -

659fefceacfacd5b9de8842257f9afad52352bcc/original_659fefceacfacd5b9de8842257f9afad52352bcc.jpg>```

Apparently it cannot find the original file, even though it exists in the S3-Bucket (I checked this at the AWS-Console).

I am using:

```
paperclip (3.0.2)
```

and

```
GIT
  remote: https://github.com/tommeier/delayed_paperclip.git
  revision: 425edcdb46b6429a0af9847c090a90ad1658d6f7
  specs:
    delayed_paperclip (2.4.5.1)
      paperclip (>= 2.4.5)
```

Here is my model-code:

```
has_attached_file :image,
    storage: :s3,
    styles: {
      original: "#{(1200 * 1600)}@",
      thumb: "#{(100 * 75)}@"
    },
    bucket: ENV['S3_BUCKET_NAME'],
    s3_credentials: {
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
    },
    url: ":s3_eu_url",
    path: ":hash/:style_:hash.:extension",
    hash_secret: "something"

    process_in_background :image
```

where s3_eu_url is:

```
Paperclip.interpolates(:s3_eu_url) do |att, style|
    "#{att.s3_protocol}://s3-eu-west-1.amazonaws.com/#{att.bucket_name}/#{att.path(style)}"
end
```

Any suggestions on how to fix this?

Kind regards

Nils

**Comment by maxguzenski** [comment]
I have same problem...

**Comment by lacco** [comment]
I could solve this issue by using Paperclip edge:

```
gem "paperclip", :git => "https://github.com/thoughtbot/paperclip.git"
```

As far as I see we have to wait for Paperclip 3.0.3 , the related pull request: https://github.com/thoughtbot/paperclip/pull/827

**Comment by NilsHaldenwang** [comment]
Well, the solution of @lacco implies this is related to paperclip, so I am closing it for now.
