### ISSUE TITLE
README doesn't entirely reflect reality

### ISSUE THREAD

**Issue by nickgrim** [jstorimer/delayed_paperclip#7]
The README says:

> To have the missing image url be outputted by paperclip while the image is being processed, all you need to do is add a #{attachment_name}_processing column to the specific model you want to enable this feature for.

...but the various files in lib/delayed/jobs all mark the attachment as having been processed _before_ they call reprocess! If the processing takes a significant amount of time, then the user will see a broken-image (as opposed to the missing-image) for the period of time between processing starting and finishing.

**Comment by jstorimer** [comment]
Quite right. There is a hole in the plugin's logic atm. I need to dig a bit deeper into the Paperclip source to get this fixed.

**Comment by jstorimer** [comment]
This lie hath been resolved as of version 0.6.4!

**Comment by jplethier** [comment]
I didn't understand how can I make the missing image appears while the video file is processing.I already add a column named video_processing to my model, but where I have to put the file that should appear while processing, and where I have to point to it?
