### ISSUE TITLE
Help testing against edge resque

### ISSUE THREAD

**Issue by steveklabnik** [jstorimer/delayed_paperclip#76]
Hey there! 

I'm gearing up to work on Resque 2.0, and I'd like to coordinate better with plugin authors to make sure stuff doesn't break.

I'd like to know a few things:
1. Can I do something to help get you testing against edge Resque?
2. Are you monkey-patching anything in Resque currently? Can 2.0 expose an API to help you not have to do that any more?
3. Do you need any help in bringing your plugin up-to-date with the latest Resque?

Thanks!

Related: https://github.com/defunkt/resque/issues/880

**Comment by jrgifford** [comment]
1. jrgifford/delayed_paperclip is now upstream.
2. Not sure, I'll be looking into this soon.
3. Don't think so. I'll check.
4. I'll have to try with latest first, then get back to you. :-)

## 

James Gifford
2162238574

**Comment by steveklabnik** [comment]
Oh hello! I'll re-open this there, then.

**Comment by steveklabnik** [comment]
Also, I corrected to the new upstream in our wiki page.

**Comment by jrgifford** [comment]
Cool. :+1:

## 

James Gifford
2162238574
