### ISSUE TITLE
Rails 3 and Paperclip callback problems

### ISSUE THREAD

**Issue by dewski** [jstorimer/delayed_paperclip#8]
Trying to use this with Rails 3 and Paperclip 2.3.1.1 I get this:

```
Loading development environment (Rails 3.0.0.beta)
irb(main):001:0> User.methods
NoMethodError: undefined method `before_avatar_post_process' for #<Class:0x10673eef0>
    from /Library/Ruby/Gems/1.8/gems/activerecord-3.0.0.beta/lib/active_record/base.rb:1300:in `method_missing'
    from /Library/Ruby/Gems/1.8/gems/delayed_paperclip-0.6.4/lib/delayed/paperclip.rb:47:in `send'
    from /Library/Ruby/Gems/1.8/gems/delayed_paperclip-0.6.4/lib/delayed/paperclip.rb:47:in `process_in_background'
    from /Users/garrett/src/sites/clientend/app/models/user.rb:16
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:396:in `load_without_new_constant_marking'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:396:in `load_file'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:537:in `new_constants_in'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:395:in `load_file'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:275:in `require_or_load'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:441:in `load_missing_constant'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:91:in `const_missing_not_from_s3_library'
    from /Library/Ruby/Gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/extensions.rb:206:in `const_missing'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/dependencies.rb:103:in `const_missing'
    from (irb):1
```

JasonKing's commit for Paperclip and Rails 3 breaks the `before_#{name}_post_process` http://github.com/JasonKing/paperclip/commit/9c9082814f628a618f625158fc8507ef1578dacc . Do you have any suggestions as to what we can do to make this work again?

Thanks in advance.

**Comment by lpgauth** [comment]
Check out: http://gist.github.com/334358

I have DelayedPaperclip working with Rails3 without ActiveRecord (I'm using Redis). If you need more info I can send other patches I made to my copy...

**Comment by dewski** [comment]
Ipgauth that'd be great, I am using Resque/Redis as well. For some reason the part confusing me is being able to actually halt the `before_name_post_process` within `delayed_paperclip`. Are you not having any trouble?

With my install it works fine, it just converts them on the upload, then again when Resque/Redis hit it, defeating the purpose!

**Comment by jstorimer** [comment]
Just tried this with Paperclip 2.3.3 and Rails 3.0.0.beta4 and it worked without issue. I can see that it might be beneficial to use the new callback syntax but its not necessary for now.
